language: go

go:
  - 1.2
  - 1.3
  - tip

script:
  - go test ./

before_script:
  - psql -c 'create database inappcloud_auth_test;' -U postgres
  - psql -c 'create table users (id serial, email text, password text, token text);' -d inappcloud_auth_test -U postgres

env: DATABASE_URL=postgres://postgres@localhost/inappcloud_auth_test

matrix:
  allow_failures:
    - go: tip
